/* main.c
 * LVGL 9.3 + SDL2 minimal example that shows the image `image1`.
 *
 * Put image1.c (generated by the LVGL image converter) next to this file
 * and compile both files together, or #include "image1.c" here (see notes).
 * use https://lvgl.io/tools/imageconverter to make the .c of the image
 */

#define SDL_MAIN_HANDLED
#include <stdio.h>
#include <stdbool.h>
#include <SDL2/SDL.h>

#include "lvgl.h"
#include "drivers/sdl/lv_sdl_mousewheel.h" /* optional */
#include "drivers/sdl/lv_sdl_keyboard.h"   /* optional */

/* If you prefer to compile image1.c with this file, do NOT uncomment the next line.
   If you prefer to include the generated C directly, uncomment it instead. */
#include "image1.c"

LV_IMG_DECLARE(image1); /* declare the image descriptor produced by the converter */

#ifndef SDL_HOR_RES
#define SDL_HOR_RES 800
#endif
#ifndef SDL_VER_RES
#define SDL_VER_RES 480
#endif

/* pointer read like in your example (reads SDL_GetMouseState) */
static void pointer_read_cb(lv_indev_t * indev, lv_indev_data_t * data)
{
    (void)indev;
    int mx = 0, my = 0;
    uint32_t buttons = SDL_GetMouseState(&mx, &my);
    data->point.x = mx;
    data->point.y = my;
    data->state = (buttons & SDL_BUTTON(SDL_BUTTON_LEFT)) ? LV_INDEV_STATE_PRESSED : LV_INDEV_STATE_RELEASED;
    data->continue_reading = false;
}

int main(void)
{
    /* 1) Init SDL */
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_EVENTS) != 0) {
        fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    /* 2) Init LVGL */
    lv_init();

#ifndef WIN32
    setenv("DBUS_FATAL_WARNINGS", "0", 1);
#endif

    /* 3) Create LVGL display + SDL window using the LVGL SDL helper */
    lv_display_t * disp = lv_sdl_window_create(SDL_HOR_RES, SDL_VER_RES);
    if (!disp) {
        fprintf(stderr, "lv_sdl_window_create failed\n");
        SDL_Quit();
        return 1;
    }

    /* 4) Optional: create other SDL-based input devices */
    (void)lv_sdl_mousewheel_create(); /* optional */
    (void)lv_sdl_keyboard_create();   /* optional */

    /* 5) Create a custom LVGL pointer input device that reads SDL_GetMouseState directly */
    lv_indev_t * my_mouse = lv_indev_create();
    if (my_mouse) {
        lv_indev_set_type(my_mouse, LV_INDEV_TYPE_POINTER);
        lv_indev_set_read_cb(my_mouse, pointer_read_cb);
    }

    SDL_ShowCursor(SDL_ENABLE);

    /* 6) Build the UI: display the image 'image1' */
    lv_obj_t * scr = lv_scr_act();

    /* Create image object and set the source to 'image1' */
    lv_obj_t * img = lv_img_create(scr);
    lv_img_set_src(img, &image1);

    /* Center the image on the screen */
    lv_obj_center(img);

    /* If you want the window to be exactly the image size, uncomment the following:
       lv_obj_set_size(img, image1.header.w, image1.header.h);
       // and recreate the SDL window with those exact dimensions instead of SDL_HOR/VER_RES.
    */

    /* 7) Main loop: tick + handler */
    Uint32 lastTick = SDL_GetTicks();
    bool running = true;
    while (running) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                running = false;
            }
            /* Don't consume mouse events — pointer_read_cb uses SDL_GetMouseState */
        }

        Uint32 now = SDL_GetTicks();
        uint32_t diff = now - lastTick;
        if (diff) {
            lv_tick_inc(diff);
            lastTick = now;
        }

        lv_timer_handler();
        SDL_Delay(1);
    }

    /* Cleanup */
    /* Depending on the LVGL build you may call lv_display_delete()/lv_indev_delete() here. */
    SDL_Quit();
    return 0;
}
